In [1]:
import numpy as np
import pandas as pd

In [2]:
syn_df = pd.read_csv('/Users/pin.lyu/Documents/BC_Folder/NLP/Data/synthetic_reformat.csv')

train_df = pd.read_json("/Users/pin.lyu/Documents/BC_Folder/NLP/Data/pii-detection-removal-from-educational-data/train.json")

test_df = pd.read_json("/Users/pin.lyu/Documents/BC_Folder/NLP/Data/pii-detection-removal-from-educational-data/test.json")

test_df.head()

,document,full_text,tokens,trailing_whitespace
0,7,Design Thinking for innovation reflexion-Avril...,"[Design, Thinking, for, innovation, reflexion,...","[True, True, True, True, False, False, True, F..."
1,10,Diego Estrada\n\nDesign Thinking Assignment\n\...,"[Diego, Estrada, \n\n, Design, Thinking, Assig...","[True, False, False, True, True, False, False,..."
2,16,Reporting process\n\nby Gilberto Gamboa\n\nCha...,"[Reporting, process, \n\n, by, Gilberto, Gambo...","[True, False, False, True, True, False, False,..."
3,20,Design Thinking for Innovation\n\nSindy Samaca...,"[Design, Thinking, for, Innovation, \n\n, Sind...","[True, True, True, False, False, True, False, ..."
4,56,Assignment: Visualization Reflection Submitt...,"[Assignment, :, , Visualization, , Reflecti...","[False, False, False, False, False, False, Fal..."

In [3]:
train_df.head()

,document,full_text,tokens,trailing_whitespace,labels
0,7,Design Thinking for innovation reflexion-Avril...,"[Design, Thinking, for, innovation, reflexion,...","[True, True, True, True, False, False, True, F...","[O, O, O, O, O, O, O, O, O, B-NAME_STUDENT, I-..."
1,10,Diego Estrada\n\nDesign Thinking Assignment\n\...,"[Diego, Estrada, \n\n, Design, Thinking, Assig...","[True, False, False, True, True, False, False,...","[B-NAME_STUDENT, I-NAME_STUDENT, O, O, O, O, O..."
2,16,Reporting process\n\nby Gilberto Gamboa\n\nCha...,"[Reporting, process, \n\n, by, Gilberto, Gambo...","[True, False, False, True, True, False, False,...","[O, O, O, O, B-NAME_STUDENT, I-NAME_STUDENT, O..."
3,20,Design Thinking for Innovation\n\nSindy Samaca...,"[Design, Thinking, for, Innovation, \n\n, Sind...","[True, True, True, False, False, True, False, ...","[O, O, O, O, O, B-NAME_STUDENT, I-NAME_STUDENT..."
4,56,Assignment: Visualization Reflection Submitt...,"[Assignment, :, , Visualization, , Reflecti...","[False, False, False, False, False, False, Fal...","[O, O, O, O, O, O, O, O, O, O, O, O, B-NAME_ST..."

In [11]:
train_df.shape

(6807, 5)

In [4]:
syn_df.head()

,ESSAY,tokens,trailing_whitespace,labels
0,The digital age has blurred the lines between ...,"['The', 'digital', 'age', 'has', 'blurred', 't...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
1,The digital age has irrevocably woven itself i...,"['The', 'digital', 'age', 'has', 'irrevocably'...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
2,The question of identity in the digital age is...,"['The', 'question', 'of', 'identity', 'in', 't...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
3,The flickering fluorescent lights of the unive...,"['The', 'flickering', 'fluorescent', 'lights',...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
4,## The Unexpected Detour: Finding Community in...,"['The', 'Unexpected', 'Detour', 'Finding', 'Co...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."

In [5]:
# Assuming you have a pandas DataFrame named df that contains the column 'ESSAY'

syn_df.rename(columns={'ESSAY': 'full_text'}, inplace=True)

In [6]:
syn_df.head()

,full_text,tokens,trailing_whitespace,labels
0,The digital age has blurred the lines between ...,"['The', 'digital', 'age', 'has', 'blurred', 't...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
1,The digital age has irrevocably woven itself i...,"['The', 'digital', 'age', 'has', 'irrevocably'...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
2,The question of identity in the digital age is...,"['The', 'question', 'of', 'identity', 'in', 't...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
3,The flickering fluorescent lights of the unive...,"['The', 'flickering', 'fluorescent', 'lights',...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
4,## The Unexpected Detour: Finding Community in...,"['The', 'Unexpected', 'Detour', 'Finding', 'Co...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."

In [7]:
# I want to row bined the syn_df and train_df. How can I do that?

row_binded_df = pd.concat([syn_df, train_df], axis=0)

In [8]:
row_binded_df.head()

,full_text,tokens,trailing_whitespace,labels,document
0,The digital age has blurred the lines between ...,"['The', 'digital', 'age', 'has', 'blurred', 't...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ...",NaN
1,The digital age has irrevocably woven itself i...,"['The', 'digital', 'age', 'has', 'irrevocably'...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ...",NaN
2,The question of identity in the digital age is...,"['The', 'question', 'of', 'identity', 'in', 't...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ...",NaN
3,The flickering fluorescent lights of the unive...,"['The', 'flickering', 'fluorescent', 'lights',...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ...",NaN
4,## The Unexpected Detour: Finding Community in...,"['The', 'Unexpected', 'Detour', 'Finding', 'Co...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ...",NaN

In [9]:
# After modification

row_binded_df = row_binded_df.drop(columns=['document'])

In [10]:
row_binded_df

,full_text,tokens,trailing_whitespace,labels
0,The digital age has blurred the lines between ...,"['The', 'digital', 'age', 'has', 'blurred', 't...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
1,The digital age has irrevocably woven itself i...,"['The', 'digital', 'age', 'has', 'irrevocably'...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
2,The question of identity in the digital age is...,"['The', 'question', 'of', 'identity', 'in', 't...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
3,The flickering fluorescent lights of the unive...,"['The', 'flickering', 'fluorescent', 'lights',...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
4,## The Unexpected Detour: Finding Community in...,"['The', 'Unexpected', 'Detour', 'Finding', 'Co...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
...,...,...,...,...
6802,EXAMPLE – JOURNEY MAP\n\nTHE CHALLENGE My w...,"[EXAMPLE, –, JOURNEY, MAP, \n\n, THE, CHALLENG...","[True, True, True, False, False, True, True, F...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
6803,Why Mind Mapping?\n\nMind maps are graphical r...,"[Why, Mind, Mapping, ?, \n\n, Mind, maps, are,...","[True, True, False, False, False, True, True, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
6804,"Challenge\n\nSo, a few months back, I had chos...","[Challenge, \n\n, So, ,, a, few, months, back,...","[False, False, False, True, True, True, True, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
6805,Brainstorming\n\nChallenge & Selection\n\nBrai...,"[Brainstorming, \n\n, Challenge, &, Selection,...","[False, False, True, True, False, False, True,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
6806,Mind Mapping\n\nChallenge\n\nMy consulting tea...,"[Mind, Mapping, \n\n, Challenge, \n\n, My, con...","[True, False, False, False, False, True, True,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."

In [14]:
# output directory 
import os
output_dir = "/Users/pin.lyu/Documents/BC_Folder/NLP/Data/"

# CSV

row_binded_df.to_csv(os.path.join(output_dir, "merged_data.csv"), index=False)